extend threading API
loud-hound/woofer pull request #14
Opened 2017-02-04 12:53 UTC by mihacooper

2017-02-04 19:55 UTC, mihacooper commented on src/cpp/threading.h
> +        std::atomic<ThreadCommands> hookCmd;
переименую просто в command

2017-02-05 22:54 UTC, IUdalov requested changes

2017-02-05 22:54 UTC, IUdalov commented on src/cpp/stored-object.cpp
> +    sol::object unpack(sol::this_state state) const final {
noexcept ты отовсюду убрал?
Изменения в некоторых файлах - это просто удаление  noexcept. Наверное можно. Только нужно это обсудить.

2017-02-05 22:54 UTC, IUdalov commented on src/cpp/threading.h
> +        THREAD_STATUS_FAILED,
С++14 же :)
```
enum class ThreadStatus {
    Running,
    Paused,
    ...
}
```

2017-02-05 22:54 UTC, IUdalov commented on src/cpp/lua-module.cpp
> +static sol::object createThreadFactory(sol::this_state lua, const sol::function& func) {
`static` здесь лишний

2017-02-05 22:54 UTC, IUdalov commented on src/cpp/threading.cpp
> +namespace lua_this_thread {
А зачем здесь отдельный namespace?

2017-02-05 22:54 UTC, IUdalov commented on src/cpp/threading.h
> +    void sleep(int64_t, sol::optional<std::string>) noexcept;
По хорошему здесь не хватает параметра по умолчанию:/
Для формата.
Пока наверно можно подождать, но лучше бы добавить TODO:

2017-02-05 22:54 UTC, IUdalov commented on src/cpp/threading.h
> +class ThreadFactory {
Какая то странная схема получилась.
Может проще сделать класс потока. А все остальное написать в lua?
А то сейчас какая то мутная схема получилась.

2017-02-06 06:42 UTC, mihacooper commented on src/cpp/stored-object.cpp
> +    sol::object unpack(sol::this_state state) const final {
Не везде, мы же обсуждали. Я убрал там, где они действительно могут быть выброшены

2017-02-06 06:49 UTC, mihacooper commented on src/cpp/threading.h
> +    void sleep(int64_t, sol::optional<std::string>) noexcept;
Параметра по умолчанию для чего?

2017-02-06 06:49 UTC, mihacooper commented on src/cpp/threading.h
> +        THREAD_STATUS_FAILED,
Ок

2017-02-06 06:50 UTC, mihacooper commented on src/cpp/lua-module.cpp
> +static sol::object createThreadFactory(sol::this_state lua, const sol::function& func) {
Ограничивает область видимости функции... Ну да ладно)

Их бы вообще в классы попрятать

2017-02-06 06:52 UTC, mihacooper commented on src/cpp/threading.cpp
> +namespace lua_this_thread {
Изначально хотел отделить "статические" функции API от всего остального, можно убрать, не принципиально

2017-02-06 06:55 UTC, mihacooper commented on src/cpp/threading.h
> +class ThreadFactory {
Убрать можно, но тогда придется дублировать API фабрики в треде, да и я не рискну,  т.к. подумал, что в будущем может понадобиться какая-то плюсовая логика здесь и все придется переписывать или костылять. Как бы cpp более универсально получается

2017-02-06 14:47 UTC, IUdalov commented on src/cpp/threading.h
> +    void sleep(int64_t, sol::optional<std::string>) noexcept;
Для  строки (по умолчанию  ms).

2017-02-07 08:21 UTC, merged